// <auto-generated />
using System;
using FestoVideoStream.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace FestoVideoStream.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190509173233_StreamStatusIsMapped")]
    partial class StreamStatusIsMapped
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("FestoVideoStream.Entities.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Config");

                    b.Property<string>("IpAddress")
                        .IsRequired();

                    b.Property<DateTime?>("LastActivityDate");

                    b.Property<DateTime?>("LastStreamDate");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<bool>("StreamStatus");

                    b.HasKey("Id");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("FestoVideoStream.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Login");

                    b.Property<string>("PasswordHash");

                    b.HasKey("Id", "Login");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
